[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
baseURL = "https://law.xuufaa.com/"
languageCode = "zh-cn"
title = "法考笔记 · xuufaa"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    name = "民法"
    url = "/civil/"
    weight = 1
  [[menu.main]]
    name = "刑法"
    url = "/criminal/"
    weight = 2
  [[menu.main]]
    name = "行政法"
    url = "/administrative/"
    weight = 3
  [[menu.main]]
    name = "诉讼法"
    url = "/litigation/"
    weight = 4
  [[menu.main]]
    name = "宪法"
    url = "/constitution/"
    weight = 5
  [[menu.main]]
    name = "商经法"
    url = "/economic/"
    weight = 6
  [[menu.main]]
    name = "主观题"
    url = "/essay/"
    weight = 7

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  defaultTheme = "light"

[outputs]
  home = ["HTML", "JSON"]
